---
title: "Tilapia Imports"
author: "Paloma Cartwright"
date: "13/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

```{r}

us_tilapia_imports <- read_csv(here::here("data", "us_tilapia_imports.csv")) 

tilapia <-  pivot_longer(data = us_tilapia_imports, 
                         cols = -country, 
                         names_to = "year", 
                         values_to = "imports")
tilapia$year <- as.numeric(tilapia$year)


yearly_tilapia_tot <- tilapia %>% 
  dplyr::group_by(year) %>% 
  summarize(total = sum(imports, na.rm = TRUE))


ggplot(data = yearly_tilapia_tot, aes(x = year, y = total)) +
  geom_line() +
  labs(title = "US Tilapia Imports by Year", 
       x = "Year",
       y = "Total Imports (thousands of pounds)")

ggsave(here::here("figs", "yearly_total_imports.png"))
  

```

```{r}


latin_america_imports <- tilapia %>% 
  filter(country %in% c("Ecuador", "Honduras", "Costa Rica", "Mexico")) 

l_a_imports_subset <- latin_america_imports %>% 
  group_by(country, year) %>% 
  summarize(total = sum(imports, na.rm = TRUE))

ggplot(l_a_imports_subset, aes(x = year, y = total)) +
  geom_point(aes(color = country)) +
  geom_line(aes(color = country)) + 
  labs(title = "US Tilapia Imports from Latin American Countries", 
       x = "Year", 
       y = "Total Imports (Thousands of Pounds)", 
       color = "Country")

ggsave(here::here("figs", "latin_america_imports.jpg"))
```

